### ISSUE TITLE
Safe usage in mainnet

### ISSUE THREAD

**Issue by youssefgh** [sipa/bech32#39]
Am creating a wallet for testnet and mainnet.
Am wondering is it safe to enable the use of bech32 addresses in mainnet now ?
I already asked this question in [stackexchange](https://bitcoin.stackexchange.com/questions/65192/are-bech32-addresses-safe-for-mainnet-usage) but it look like nobody have any idea
What worries me is the 'draft' status of this BIP
Thanks a lot for your contribution !

**Comment by afk11** [comment]
Asked on IRC a while back, the draft status shouldn't deter you using bech32 at this point. Wallets and explorers already generating these addresses, and the spec hasn't been changed in months.

**Comment by youssefgh** [comment]
Thanks a lot ! happy to here that :D
