### ISSUE TITLE
bech32 decoder looks for the first '1' as the HRP separator, not the last '1' as specified

### ISSUE THREAD

**Issue by daira** [sipa/bech32#44]
https://github.com/sipa/bech32/blob/60848c2e9f214910d98636773fae103ea948be6f/ref/c/segwit_addr.c#L95-L99

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#bech32 says that the last '1' in the string is the HRP separator. The reference code is inconsistent with that [and with Bitcoin Core](https://github.com/bitcoin/bitcoin/blob/f34c8c466a0e514edac2e8683127b4176ad5d321/src/bech32.cpp#L168).

**Comment by sipa** [comment]
I don't think so; `(*data_len)` increments, but is used as a negative in the index to `input`: `input[(input_len - 1) - *data_len]`, so it counts backwards.

There is also a unit test for an HRP that includes a "1", which both the C and C++ code pass.

**Comment by daira** [comment]
You're right, sorry for the invalid report.
