### ISSUE TITLE
How generate bech with wrong ecoding ?

### ISSUE THREAD

**Issue by mraksoll4** [sipa/bech32#75]
How generate bech with wrong encoding i need this for tests.

**Comment by apoelstra** [comment]
In general, to compute invalid data for test vectors, you need to edit the code. It would be quite difficult for us to expose the ability to mangle checksums in various ways, and the value is only for testing. This is true for pretty-much any implementation of any spec.

Bech32 is defined in [BIP 173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) and there are some precomputed test vectors there.
