### ISSUE TITLE
bip72b payment requests and qrcodes

### ISSUE THREAD

**Issue by the9ull** [sipa/bech32#8]
In alphanumeric qrcode encoding it is not possible to encode a bip72b – `bitcoin:?r=https://dev/null` – payment requests urls because `?` and `=` are missed.

We could introduce a new bip72 URI to use alphanumeric encoding in qrcode payment requests

(It would be more like `BITCOIN:*HTTPS://DEV/NULL`)

**Comment by sipa** [comment]
@the9ull Alphanumeric encoding is decided on a character-by-character basis, and is advantageous as soon as there are more than a few consecutive uppercase/numeric characters.

Having a few lowercase and/or non-alphanumeric characters in a QR code doesn't hurt. Switching between uppercase and lowercase all the time does.
